### ISSUE TITLE
Limit drop table

### ISSUE THREAD

**Issue by Altorffer** [konwboj/MagicClover#4]
The reason I am suggesting this is because I was using this mod in conjunction with a few other mods and some of the items it ended up rewarding me were internal blocks for those mods. One of them ended up corrupting my savegame, as I kept getting exceptions (the item in question had no icon).

Basically, I can see 3 ways of going about this:

1 - Adding a configuration option that allows a user to specify the population from which the item is chosen; either the full registry or just vanilla items (I'd imagine limiting it to just vanilla is fairly straightforward, codewise). Essentially, this would amount to mass white/blacklisting items.
2 - Adding checks to the generated reward; specifically, such as ensuring the item has an icon, a full name (and not just an internal abc.defg.blocktitle type of name, as these are typically internal). This to ensure the chances of getting an item that you normally would not be able to get with regular play is reduced to close to zero.
3 - Wildcard support in whitelisting/blacklisting.

Personally, I would prefer option 2 but it might be more complicated to pull off, I would fork the project and pull request a change like this myself but I am more of a C# person and have never coded a Minecraft mod so would be unsure on how to go about doing this. I'm still willing to have a look though, if you need a hand.

**Comment by konwboj** [comment]
Only items with localized names now drop from clover and added banned mods field to config. No icon for item/block is a hacky solution and I will try to think about something else. 
For now, this should work.

**Comment by Altorffer** [comment]
I agree, in retrospect. It does seem somewhat hacky indeed. I'll ponder on it as well, maybe I can come up with a different suggestion. Something a bit more robust, more reliable and less specific. There's bound to be a general rule of thumb that can be applied to which items are likely to crash Minecraft (either the server or the client).

**Comment by Altorffer** [comment]
How about only rewarding items that have a crafting recipe or are an ingredient in a crafting recipe? It would amount to a single filter that would easily cover the default banned items, internal mod items (since those are not craftable) and so forth, while still allowing access to essentially anything relevant.

**Comment by Blue64** [comment]
That would prevent ideas such as needing use a Clover to get the item via removing all other recipes. Plus there's items that have non standard recipes in various mods (ThaumCraft, PneumaticCraft, Blood Magic, etc.), that's a bit intensive as he'd need to code in the IIngredient portion every time another mod invents another crafting method (IC2, GregTech, Immersive Engineering, AE2, etc.), thus defeating the "nifty **little** utility mod" title of this mod lol

**Comment by Altorffer** [comment]
Well, there is such a thing as wanting to be too little and too general. As this very issue so obviously demonstrated and whereas the dev's solution does indeed cover some of the problems, it doesn't cover all corner cases. Corner such as the non-standard recipes you're mentioning. Not all items are 'safe' to have made available with a Clover. Because, being such a "nifty little utility mod", it cannot possibly see how all those items fit together. Consequently, I still maintain it is better to be safe than sorry and to simply enforce stricter rules on what can and cannot be dropped by the Clover.

-- No localized name -- Don't drop it.
-- No icon of any kind -- Don't drop it.
-- Not an ingredient or result of a crafting recipe -- Don't drop it.

Yes, it's strict but it should at least guarantee that no savegame corruption takes place. The savegame corruption I was confronted with as a result of Clover forced me to restart that world. That should be avoided at all costs, I'd say. Because, well, ever since that occured, I've avoided this particular mod whenever throwing together my own private modpack. Until I'm satisfied the mod actually can be trusted.

**Comment by Blue64** [comment]
the localized name, I could understand, as 99% of perfectly valid items these days have localized items, but sometimes errors happen to images (binnie's mod's Geranium has a messed up image file for example), so images is kind of a grey area, and chances are that if it has a localized name, the mod author at the very least trusts the item enough to have it drop (albeit a black & purple checkerboard).

You could always just use the blacklist function you know, specify the item that destroyed your world, and now it can't spawn, problem solved.

He already has Bedrock on the blacklist using the standard format of ```mod:name``` lol it's all there in the config. I have had no issues related directly to Magic Clover it's self, as I always actually utilize the config which I have been given.

I recently had a cross-mod issue arise while adding some new mods, but that's got nothing to do with something the config can fix already. this issue can already be fixed via config.
```
# Configuration file

general {
	# These items will not drop from clover. Supports item names (like minecraft:stone)!
	S:"Banned Items" <
		minecraft:flowing_lava
		minecraft:powered_comparator
		minecraft:water
		minecraft:flowing_water
		minecraft:lava
		minecraft:tripwire
		minecraft:farmland
		minecraft:unpowered_comparator
		minecraft:standing_sign
		minecraft:piston_extension
		minecraft:pumpkin_stem
		minecraft:unpowered_repeater
		minecraft:melon_stem
		minecraft:bedrock
		minecraft:piston_head
		minecraft:redstone_wire
		minecraft:wall_sign
		minecraft:spawn_egg
		minecraft:mob_spawner
		minecraft:powered_repeater
		minecraft:enchanted_book
		minecraft:tripwire_hook
		minecraft:command_block_minecart
		minecraft:farmland
		minecraft:lit_furnace
		minecraft:barrier
		minecraft:written_book
		minecraft:firework_charge
		minecraft:fireworks
	 >
	# Items from these mods will not drop from clover. Entries on this list are mod ids. You can find them in Mods tab (main menu). You can treat "minecraft" as a mod here.
	S:"Banned Mods" <
	 >
```
just saying.

**Comment by Altorffer** [comment]
And... just sayin' -- Magic Clover did not add enough to the gameplay for it to warrant actually having to spend time trying to figure out how to add an item to its blacklist if the item in question had a name along the lines of PyVeVlOYRv.XZpjBBnARk.ruavxQoCSw (as in, something illegible).

Honestly, there should be no need to have to investigate every single item added by every single mod; particularly because there are mods that add hundreds if not thousands of items. I can't very well be expected to individually check all of them for stability in conjunction with Magic Clover, now can I? Point being -- you like the mod, I no longer really do. The concept is nice, the execution could be improved upon. To each his own. ;)

**Comment by Blue64** [comment]
MineTweaker mod offers a text command where you can hold the item in your hand and type ```/mt hand``` and it copies the item name to your clipboard along with the Meta data, there's probably also at least 3 other mods that dump the entire Item Registry to a text file. The only mods I can think of that add even remotely close to a thousand items is Chisel and it's similar mods (even Extra Utilities is only a few hundred, I should know, I'm actually indexing my Item Lists soon for total customization) AE2 could in theory add that many, but that's just Facades, and they'd have the same problem, along with the BuildCraft Pipe Covers. Did you by chance try reporting this crash to the mod that actually made the item that crashed your game? It appears to me that other than a feature request of stricter drop filters, this post is far out of place, as the Clover it's self didn't cause the crash, it simply gave you the item which caused the crash. You also left out a few key features, such as your Clover version, your MineCraft version, your Forge Version, and your Operating System (sometimes it's something as simple as a missed ```\``` or ```;```, so the OS can be important), you also forgot to tell which items it gave that caused the issue, all you said was "```I was using this mod in conjunction with a few other mods and some of the items it ended up rewarding me were internal blocks for those mods. One of them ended up corrupting my savegame, as I kept getting exceptions (the item in question had no icon).```" which if I'm not mistaken is actually fixed in version 1.7.10 of Forge (I have used countless items and blocks both which have no icons), as it generates a "default" look of a Pink/Black checkerboard pattern (which is a visual artifact because that is the standard background for an invisible section of an image)

**Comment by Altorffer** [comment]
And yet, in spite all of that, I never saw any crash similar to the one I experienced as a result of Clover; even when just removing Clover and keeping all other mods intact and in place. By now, it's been too long for me to accurately remember exactly which mod it was and which item it was but the point remains the same -- For me to trust Clover I would have had to manually add ALL items I perceive to be internally used by their respective mods to Clover's exception list.

Facts:
- Removing Clover and only Clover, no other mods made the collection of mods I was running at the time perfectly stable. No errors, no crashes, no exceptions, not even chunk loading errors or anything else.
- Forge was not at fault directly; it was in fact a Minecraft exception, so the crash was rather extreme. Unrecoverable.
- Please, don't lecture me on end of line characters. Checked my GitHub profile yet? I do know a fair bit about coding. ;)
- There is no version 1.7.10 of Forge; there is a version of Forge which is intended for Minecraft version 1.7.10 but Forge's version number by now, for MC 1.7.10 is 10.13.4.1558. As in, a Forge version 1.7.10 would be ancient. ;)

Anyhow, we can debate this until we both see blue in the face but, ultimately, my conclusion still stands -- you still like the mod, you still trust the mod, I don't. I already closed this issue since I have no intention whatsoever of using Clover ever again, I'd rather code my own version and beyond that, Clover's dev has also made it abudantly clear my suggested approach was unappealing to them. Hence the lack of need for this issue, call it a "WONTFIX", if you will. ;)

**Comment by Blue64** [comment]
He added ⅓ of your suggestions, and was looking into possibly more stuff.

You understand what I meant, I said 1.7.10 because there's Forge for 1.8 & Forge for 1.6 as well, so if you play in 1.6, and you don't have Forge removing erroring entities, then it's no wonder why it became unrecoverable.

Clover didn't create the instability, it only exposed it. It's completely possible to get "internal" blocks that don't crash your game, such as the MineCraft Piston Heads, or the plant stalks for wheat, melon, pumpkin, etc. My point is that it's not Clover's fault your result crashed your world, Clover threw no error, it just simply did what it was supposed to do, the fault lies within the other end of the spectrum, the block that spawned, a valid block, but wasn't programmed completely, so it threw a world killing error.

On a related note: Spawn Eggs. Some of the first 50 Meta data has names, NBT, a picture, and is still an internal block.

The WildCard support is a good idea:
```
# Any Mod that has anything to do with Coal (Mod:PrefixItemSufix:Meta)
*:*coal*:*
# Coal, Charcoal, Coke Coal, etc.

# Anything in a specific mod with a specific Meta (Mod:Item:Meta)
minecraft:*:13
# useful if you're superstitious lol

# Specific Mod, Specific Item, WildCard Meta
minecraft:coal:*
# this should also be the default if we forget the Meta.
```
